language: python
python:
  - "2.7"
install: "pip install -r flaskapp/requirements.txt"
script:
  - cd flaskapp
  - touch settings.py
  - python -c 'from uuid import uuid4; print uuid4().hex' > secrets
  - python -m unittest discover -v tests
